version: '3.8'

services:
  # Next.js应用
  app:
    build: .
    container_name: leveling-zone-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VERCEL=0
    volumes:
      - ./data/db:/app/data/db
      - ./public/db:/app/public/db
    networks:
      - caddy-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Caddy反向代理
  caddy:
    image: caddy:2-alpine
    container_name: leveling-zone-caddy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    networks:
      - caddy-net
    depends_on:
      app:
        condition: service_healthy
    environment:
      - CADDY_ADMIN=0.0.0.0:2019

  # 可选：数据库文件下载器（首次部署时）
  db-downloader:
    build: .
    container_name: leveling-zone-downloader
    command: npm run download-db-local
    volumes:
      - ./data/db:/app/data/db
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    networks:
      - caddy-net
    restart: "no"  # 只运行一次

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  caddy-net:
    driver: bridge 
