import { getDbPath } from '@/utils/dbPath';
import { DATABASE_FILES } from './config';

/**
 * 获取数据库文件的完整路径
 */
export const DB_PATHS = {
  MAXMIND: {
    CITY: getDbPath(DATABASE_FILES.MAXMIND.CITY),
    COUNTRY: getDbPath(DATABASE_FILES.MAXMIND.COUNTRY),
    ASN: getDbPath(DATABASE_FILES.MAXMIND.ASN),
  },
  DBIP: {
    CITY: getDbPath(DATABASE_FILES.DBIP.CITY),
    COUNTRY: getDbPath(DATABASE_FILES.DBIP.COUNTRY),
    ASN: getDbPath(DATABASE_FILES.DBIP.ASN),
  },
  IP2LOCATION: {
    CITY: getDbPath(DATABASE_FILES.IP2LOCATION.CITY),
    PROXY: getDbPath(DATABASE_FILES.IP2LOCATION.PROXY),
    ASN: getDbPath(DATABASE_FILES.IP2LOCATION.LITE_ASN),
  },
  IPINFO: {
    COUNTRY_ASN: getDbPath(DATABASE_FILES.IPINFO.COUNTRY_ASN),
  },
  IPTOASN: getDbPath(DATABASE_FILES.IPTOASN),
  QQWRY: getDbPath(DATABASE_FILES.QQWRY),
  GEOCN: getDbPath(DATABASE_FILES.GEOCN),
  ASN_INFO: getDbPath(DATABASE_FILES.AS_INFO),
};
